### ISSUE TITLE
Add Mineclone 2 support

### ISSUE THREAD

**Issue by wuniversales** [NathanSalapat/tombs#1]
https://forum.minetest.net/viewtopic.php?f=47&t=20935

**Comment by NathanSalapat** [comment]
This really doesn't help me at all. As somebody that doesn't play Mineclone I have no idea what mod:nodes I would be adding to the supported list.
Adding support for mods is very easy, look here: https://github.com/NathanSalapat/tombs/blob/master/api.txt
